### ISSUE TITLE
Cannot delete volumes created on docker 1.11

### ISSUE THREAD

**Issue by matt-deboer** [vmware/docker-volume-vsphere#1439] opened 2017-06-19 22:41 UTC
After building the 0.14 version, I see the following error when attempting `docker volume rm` on a newly created volume:
```
$ > docker volume create -d vsphere --name test-volume-1
test-volume-1
```

```
$ > docker volume rm test-volume-1
Error response from daemon: Error while removing volume test-volume-1: remove test-volume-1: VolumeDriver.Remove: Remove failure - volume is still mounted.  volume=test-volume-1, refcount=1
```

**Comment by pshahzeb** [comment] 2017-06-19 23:27
@matt-deboer Thank you.
I am looking into it and trying to reproduce.
By any chance if you have logs (ESX side and VM side), it would be helpful to narrow down sooner.
[ How to get logs? See this.](https://github.com/vmware/docker-volume-vsphere#logging)

**Comment by pshahzeb** [comment] 2017-06-20 01:09
Hi @matt-deboer,

We are able to reproduce this at our end. The issue is about the docker client API version that we moved up with release 0.13. Docker 1.11 supports client API version 1.23 and we moved it to 1.24 which is supported by docker 1.12 and above. This mismatch caused blocks the driver to stabilize. We improved the message in such case (when driver is not fully initialized) #1352

We did a quick check to downgrade the docker client API version to 1.23 and it works. This fix can make the docker-volume-vsphere driver work with docker 1.11

However, we recommend you to upgrade the docker. With docker version 1.13  and docker-volume-vsphere 0.13 we moved to managed plugin. Upgrading would enable you to take advantage of it.

If you have need to to stay on docker 1.11, let us know and we can consider the option of private build.

**Comment by matt-deboer** [comment] 2017-06-20 03:02
Hi Shahzeb,
Thanks for looking into this; unfortunately, we have to keep running docker
1.11 for a short period of time--but we're fine with maintaining a private
build of the 1.23 API back-port until we can upgrade. I'm happy to apply
this in my own fork--would you mind pointing me to the places you modified
to make the quick-fix in order to save me a little time?

Thanks.

**Comment by pshahzeb** [comment] 2017-06-20 03:27
Sure.
The only place that needs to changed is this line.
https://github.com/vmware/docker-volume-vsphere/blob/master/vmdk_plugin/utils/refcount/refcnt.go#L90

it is "v1.24". It needs to be "v1.23" to make it work with docker 1.11

Thanks.

**Comment by matt-deboer** [comment] 2017-06-20 03:28
Excellent. Thanks much!

**Comment by shuklanirdesh82** [comment] 2017-06-20 17:37
closing this issue as per https://github.com/vmware/docker-volume-vsphere/issues/1439#issuecomment-309631452

**Closed by shuklanirdesh82** 2017-06-20 17:37 UTC
Labels: customer, kind/bug, P0

**Comment by shuklanirdesh82** [comment] 2017-06-21 17:20
Hey @matt-deboer,

I am reaching out to you find other whether the work around suggested at https://github.com/vmware/docker-volume-vsphere/issues/1439#issuecomment-309634549 unblocks you or not. 

Can you please confirm at your earliest?

Thanks!

**Comment by matt-deboer** [comment] 2017-06-21 18:21
we are unblocked; thanks again!

**Comment by shuklanirdesh82** [comment] 2017-06-21 19:03
Thanks @matt-deboer for confirming! I'm glad hearing that.
