### ISSUE TITLE
[Windows VM] Writing data to the volume using docker run command fails

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1909] opened 2017-09-27 23:53 UTC
I am using windows vm for executing the test

Steps: 
1. Created a volume from windows docker vm
2. Tried to attach the volume to the container and write data to the volume using docker run command - Failed with error:  The system cannot find the path specified.

Logs have been attached at the end

------------------------------------------------

Detailed steps and their output are as follows:

1. Created a volume from windows docker vm
```
root@WIN-QBI6V8BMPGM C:\Users\root>docker volume create --driver=vsphere --name=
MyVolume -o size=1gb
myvolume
root@WIN-QBI6V8BMPGM C:\Users\root>docker volume ls
DRIVER              VOLUME NAME
vsphere             myvolume@sharedvmfs-1
vsphere             test1@sharedvmfs-1
```
2. Tried to attach volume to the container and write data to the volume. ```docker run``` command failed with error - The system cannot find the path specified.
```
root@WIN-QBI6V8BMPGM C:\Users\root>docker run -v myvolume@sharedvmfs-1:C:\vol mi
crosoft/nanoserver cmd 'echo "message_by_host1" > C:\vol\test.txt'
The system cannot find the path specified.

root@WIN-QBI6V8BMPGM C:\Users\root>
```

Logs: 
[vmdk_ops.log.1.txt](https://github.com/vmware/docker-volume-vsphere/files/1339025/vmdk_ops.log.1.txt)
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/1339026/vmdk_ops.txt)

**Comment by ashahi1** [comment] 2017-09-27 23:55
@pshahzeb or @shaominchen Can someone please take a look at this issue?

**Comment by shuklanirdesh82** [comment] 2017-09-29 18:27
#1658 is blocked due to this (confirmed with @ashahi1, Thanks Anup!)

/CC @ashahi1

**Comment by govint** [comment] 2017-10-03 06:59
I've not run docker with windows plugin yet, setting estimate to 5 to understand this a bit and check whats failing.

**Comment by govint** [comment] 2017-10-09 11:22
Starting this activity from 10/10

**Comment by govint** [comment] 2017-10-17 10:53
Docker volume is attached as expected,
root@WIN-QBI6V8BMPGM C:\Users\root>docker volume inspect testvol
[
    {
        "Driver": "vsphere",
        "Labels": {},
        "Mountpoint": "C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local\\docker-volume-vsphere\\mounts\\testvol\\",
        "Name": "testvol",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "attached to VM": "Windows-Server2016-64",
            "attachedVMDevice": {
                "ControllerPciSlotNumber": "224",
                "Unit": "0"
            },
            "capacity": {
                "allocated": "12MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Tue Oct 17 10:27:48 2017",
            "created by VM": "Windows-Server2016-64",
            "datastore": "sharedVmfs-1",
            "diskformat": "thin",
            "fstype": "ntfs",
            "status": "attached"
        }
    }
]

**Comment by govint** [comment] 2017-10-17 10:59
@ashahi1, the vmdk-ops log posted earlier doesn't have the logs to attach the volume. I'm not sure if that was an error. But I'm not reproducing the issue. If the issue repros then can we check the state of the volume that its attached and verify in the logs that the volume did attach successfully.

I'd suggest closing the issue and reopen (or new issue) if it reproduces.

**Comment by govint** [comment] 2017-10-17 11:11
Closing per above updates. Lets reopen or make a new issue if the behavior repros.

**Closed by govint** 2017-10-17 11:11 UTC
Labels: could-not-reproduce, kind/bug, mustfix, P0
