### ISSUE TITLE
The utility function govc.RetrieveVMNameFromIP() is not working properly when guestOS flips its IP address as docker IP

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1284] opened 2017-05-23 04:35 UTC
In PR #1278 we introduced a testing utility function govc.RetrieveVMNameFromIP(), which is supposed to get the VM name for the given IP by calling govmomi. During test, it turns out the function is not working properly with Photon VM - there are some issues dealing with Photon VM's guest IP. 

The usage of this function has been temporarily commented out in PR #1276.

**Comment by lipingxue** [comment] 2017-06-06 04:33
I hit this issue on Ubuntu OS too, so it looks like not specific to Photon OS.

**Comment by govint** [comment] 2017-06-06 05:27
If this function is commented out then how will other tests that are using
these work? I too had the same problem on local VM. But in CI there is no
issue. For local VM just hard code the values and verify it all works then
restore the calls to getvmname and submit to CI. Removing the function will
block a bunch of submits

**Comment by shuklanirdesh82** [comment] 2017-06-26 22:34
@ashahi1 

Can you please take care of this issue?

1. uncomment the verification code ( added as part of #1276) and invoke CI 3-4 times > if CI passed merge the change and close this PR

2. incase of observing failure let's investigate further about the issue .. (https://github.com/vmware/docker-volume-vsphere/blob/master/tests/utils/inputparams/testparams.go#L136 ... our `GetTestConfig` is consuming it and our tests are heavily dependent on and not observed any issue related with reported one so far)

**Comment by ashahi1** [comment] 2017-06-28 08:32
No longer seeing the original issue of RetrieveVMNameFromIP  method not returning vm name. Tried 3-4 times on CI but original not reproducible. 
Uncommented the part that was commented out in PR #1276 and merged as part of PR #1487.

Closing this issue now.

**Closed by ashahi1** 2017-06-28 08:32 UTC
Labels: component/test-infrastructure, P1
