### ISSUE TITLE
Unable to remove volume

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#954] opened 2017-02-23 02:15 UTC
Steps: 
[docker-volume-vsphere.txt](https://github.com/vmware/docker-volume-vsphere/files/795373/docker-volume-vsphere.txt)
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/795372/vmdk_ops.txt)

```
root@photon-TX4FfW2ET [ ~ ]# docker volume create --driver=vmdk --name=vol1 -o size=10gb 
 Error response from daemon: create vol1: Post http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: Content  Length=39 with Body length 0
```

```
root@photon-TX4FfW2ET [ ~ ]# docker volume create --driver=vmdk --name=vol1 -o size=100mb
vol1
root@photon-TX4FfW2ET [ ~ ]# docker volume inspect vol1
[
    {
        "Name": "vol1",
        "Driver": "vmdk",
        "Mountpoint": "/mnt/vmdk/vol1",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "attached to VM": "Master-VM-202",
            "capacity": {
                "allocated": "8MB",
                "size": "10GB"  <<<<<<<<<<<<<<<<============== Note it is 10GB
            },
            "clone-from": "None",
            "created": "Wed Feb 22 19:27:17 2017",
            "created by VM": "Master-VM-202",
            "datastore": "vsanDatastore",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "attached" <<<<<<<<<<<<<=================Attached
        },
        "Labels": {},
        "Scope": "global"
    }
]
root@photon-TX4FfW2ET [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vmdk                vol1@vsanDatastore

root@photon-TX4FfW2ET [ ~ ]# docker volume rm vol1
Error response from daemon: Error while removing volume vol1: remove vol1: VolumeDriver.Remove: Failed to remove volume /vmfs                                                                        /volumes/vsanDatastore/dockvols/11111111-1111-1111-1111-111111111111/vol1.vmdk, in use by VM uuid = 4221dc08-1d01-f848-c268-7                                                                        7e916527fbd.
```

Docker Engine log:
```
 journalctl -u docker.service
-- Logs begin at Wed 2017-02-22 19:10:26 UTC, end at Thu 2017-02-23 01:51:13 UTC. --
Feb 22 19:25:08 photon-TX4FfW2ET systemd[1]: Starting Docker Daemon...
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.398875789Z" level=info msg="[graphdriver] using prior storage driver \"overlay\""
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.434548380Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.435341067Z" level=warning msg="Your kernel does not support kernel memory limit."
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.435562775Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.435744771Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.435915274Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.436213160Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.436230038Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.436239855Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.436788621Z" level=warning msg="mountpoint for pids not found"
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.437300648Z" level=info msg="Loading containers: start."
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.484913855Z" level=info msg="Firewalld running: false"
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.732276695Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option -
-bip can be used to set a preferred IP address"
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.796359251Z" level=info msg="Loading containers: done."
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.796849130Z" level=info msg="Daemon has completed initialization"
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.797001087Z" level=info msg="Docker daemon" commit=23cf638 graphdriver=overlay version=1.12.1
Feb 22 19:25:09 photon-TX4FfW2ET systemd[1]: Started Docker Daemon.
Feb 22 19:25:09 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:25:09.821680294Z" level=info msg="API listen on /var/run/docker.sock"
Feb 22 19:27:20 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:27:20.021432478Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/vmdk.sock/VolumeDriver.Create: Pos
t http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: EOF, retrying in 1s"
Feb 22 19:27:21 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:27:21.022802440Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/vmdk.sock/VolumeDriver.Create: Pos
t http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: ContentLength=39 with Body length 0, retrying in 2s"
Feb 22 19:27:23 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:27:23.023319884Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/vmdk.sock/VolumeDriver.Create: Pos
t http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: ContentLength=39 with Body length 0, retrying in 4s"
Feb 22 19:27:27 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:27:27.023791136Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/vmdk.sock/VolumeDriver.Create: Pos
t http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: ContentLength=39 with Body length 0, retrying in 8s"
Feb 22 19:27:35 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:27:35.024730390Z" level=error msg="Handler for POST /v1.24/volumes/create returned error: create vol1: Post http://%2Fru
n%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: ContentLength=39 with Body length 0"
Feb 22 19:28:43 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:28:43.958619332Z" level=error msg="Handler for DELETE /v1.24/volumes/vol1 returned error: Error while removing volume vo
l1: remove vol1: VolumeDriver.Remove: Failed to remove volume /vmfs/volumes/vsanDatastore/dockvols/11111111-1111-1111-1111-111111111111/vol1.vmdk, in use by VM uuid = 4221dc08-1d01-f848-
c268-77e916527fbd."
Feb 22 19:40:46 photon-TX4FfW2ET docker[477]: time="2017-02-22T19:40:46.257226417Z" level=error msg="Handler for DELETE /v1.24/volumes/vol1 returned error: Error while removing volume vo
l1: remove vol1: VolumeDriver.Remove: Failed to remove volume /vmfs/volumes/vsanDatastore/dockvols/11111111-1111-1111-1111-111111111111/vol1.vmdk, in use by VM uuid = 4221dc08-1d01-f848-
c268-77e916527fbd."
Feb 23 01:49:36 photon-TX4FfW2ET docker[477]: time="2017-02-23T01:49:36.508531706Z" level=error msg="Handler for DELETE /v1.24/volumes/vol1@vsanDatastore returned error: Error while remo
ving volume vol1@vsanDatastore: remove vol1@vsanDatastore: VolumeDriver.Remove: Failed to remove volume /vmfs/volumes/vsanDatastore/dockvols/11111111-1111-1111-1111-111111111111/vol1.vmd
k, in use by VM uuid = 4221dc08-1d01-f848-c268-77e916527fbd."
Feb 23 01:51:13 photon-TX4FfW2ET docker[477]: time="2017-02-23T01:51:13.177866773Z" level=error msg="Handler for DELETE /v1.24/volumes/vol1@vsanDatastore returned error: Error while remo
ving volume vol1@vsanDatastore: remove vol1@vsanDatastore: VolumeDriver.Remove: Failed to remove volume /vmfs/volumes/vsanDatastore/dockvols/11111111-1111-1111-1111-111111111111/vol1.vmd
k, in use by VM uuid = 4221dc08-1d01-f848-c268-77e916527fbd."
```
========
Following files have been attached:
From Docker VM: /var/log/docker-volume-vsphere.log
From ESX: /var/log/vmware/vmdk_ops.log

**Comment by pdhamdhere** [comment] 2017-02-23 03:43
Any errors in formatting (after attach), disk becomes un-removable.

In [vmdk_driver.go](https://github.com/vmware/docker-volume-vsphere/blob/master/vmdk_plugin/drivers/vmdk/vmdk_driver.go#L255) 

```
	dev, errAttach := d.ops.Attach(r.Name, nil)
	if errAttach != nil {
		log.WithFields(log.Fields{"name": r.Name,
			"error": errAttach}).Error("Attach volume failed, removing the volume ")
		errRemove := d.ops.Remove(r.Name, nil) <<<<<<<<<<<<<
		if errRemove != nil {
			log.WithFields(log.Fields{"name": r.Name, "error": errRemove}).Warning("Remove volume failed ")
		}
		return volume.Response{Err: errAttach.Error()}
	}
```

If Attach actually succeeds on ESX then, subsequent attempt to remove volumes (`d.ops.Remove(r.Name, nil)`)  would fail because as per KV vmdk is attached to powered on VM AND ESX Service doesn't expect remove for attached disk (refCount logic).

Possible solutions:
- Do not update KV if VMDK is attached on create path for formatting. Leverage options argument to pass additional data to ESX?
- Invoke `d.ops.Detach(r.Name, nil)` before remove. This won't work if VMCI connection between VM and ESX is broken after disk is attached.

CC/ @govint

**Comment by govint** [comment] 2017-02-23 06:12
@ashahi1 can you repro the issue on your set up and post the logs for the create failure.  From the create() logic in the driver, any failure will detach the volume and remove it as well. In this case we need to figure which scenario failed and left the volume attached to the VM.

**Comment by govint** [comment] 2017-02-23 12:05
PR #941.

**Comment by msterin** [comment] 2017-02-24 04:01
Here is what happened (don't ask me why yet):

1. on 'docker volume create' , after VMDK was created,  an attach request was sent to ESX so we can format the volume
2. After the vmdk was attached, a reply was sent from ESX to the guest. 
3. On the handling of the reply, `docker-volume-vspher` service crashed with `free(): invalid pointer: 0x00007fd864000950` in `esxvmdkcmd.go:Run` on incorrect pointer in vmdkops._Cfunc_free() call (see details below).
4. Service restarted,  with the volumes not used, not formatted but attached. 

Workaround: `docker run -it -rm -v <vol>:/somewhere busybox ls /`. This will detach the volume just fine. It is not automated, but I do not think we should automate the handling of the bug which we should fix properly, at the root cause. 

----
Logs: 

* client side log  - as you can see. service started at 19:27:20
```\2017-02-22 19:27:18.56610132 +0000 UTC [DEBUG] vmdkOps.Attach name=vol1
2017-02-22 19:27:20.221741103 +0000 UTC [INFO] No config file found. Using defaults.
2017-02-22 19:27:20.222056355 +0000 UTC [INFO] Starting plugin driver=vmdk log_level=debug config="/etc/docker-volume-vsphere.conf" 
```
* client side `journalctl -u docker-volume-vsphere`
```
Feb 22 19:25:08 photon-TX4FfW2ET systemd[1]: Started "Docker Volume Driver for vSphere".
Feb 22 19:27:19 photon-TX4FfW2ET docker-volume-vsphere[457]: *** glibc detected *** /usr/local/bin/docker-volume-vsphere: free(): invalid pointer: 0x00007fd864000950 ***
...
<memory map skipped to make this log shorter>
...
Feb 22 19:27:19 photon-TX4FfW2ET docker-volume-vsphere[457]: SIGABRT: abort
Feb 22 19:27:20 photon-TX4FfW2ET docker-volume-vsphere[457]: PC=0x77bdbb m=5
Feb 22 19:27:20 photon-TX4FfW2ET docker-volume-vsphere[457]: signal arrived during cgo execution
Feb 22 19:27:20 photon-TX4FfW2ET docker-volume-vsphere[457]: goroutine 10 [syscall, locked to thread]:
Feb 22 19:27:20 photon-TX4FfW2ET docker-volume-vsphere[457]: runtime.cgocall(0x771610, 0xc82003f338, 0x0)
Feb 22 19:27:20 photon-TX4FfW2ET docker-volume-vsphere[457]: /usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc82003f300 sp=0xc82003f2d0
Feb 22 19:27:20 photon-TX4FfW2ET docker-volume-vsphere[457]: github.com/vmware/docker-volume-vsphere/vmdk_plugin/drivers/vmdk/vmdkops._Cfunc_free(0x7fd864000950)
Feb 22 19:27:20 photon-TX4FfW2ET docker-volume-vsphere[457]: ??:0 +0x36 fp=0xc82003f338 sp=0xc82003f300
Feb 22 19:27:20 photon-TX4FfW2ET docker-volume-vsphere[457]: github.com/vmware/docker-volume-vsphere/vmdk_plugin/drivers/vmdk/vmdkops.EsxVmdkCmd.Run(0xc82023e6c0, 0x9a5028, 0x6, 0xc82023f1d8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Feb 22 19:27:20 photon-TX4FfW2ET docker-volume-vsphere[457]: /go/src/github.com/vmware/docker-volume-vsphere/vmdk_plugin/drivers/vmdk/vmdkops/esx_vmdkcmd.go:121 +0x8be fp=0xc82003f508 sp=0xc82003f338
Feb 22 19:27:20 photon-TX4FfW2ET docker-volume-vsphere[457]: github.com/vmware/docker-volume-vsphere/vmdk_plugin/drivers/vmdk/vmdkops.VmdkOps.Attach(0x7fd87c48fa50, 0xc82023e6c0, 0xc82023f1d8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Feb 22 19:27:20 photon-TX4FfW2ET docker-volume-vsphere[457]: /go/src/github.com/vmware/docker-volume-vsphere/vmdk_plugin/drivers/vmdk/vmdkops/vmdkops.go:65 +0x19f fp=0xc82003f5c0 sp=0xc82003f508
Feb 22 19:27:20 photon-TX4FfW2ET docker-volume-vsphere[457]: github.com/vmware/docker-volume-vsphere/vmdk_plugin/drivers/vmdk.(*VolumeDriver).Create(0xc82021eaa0, 0xc82023f1d8, 0x4, 0xc82027c810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Feb 22 19:27:20 photon-TX4FfW2ET docker-volume-vsphere[457]: /go/src/github.com/vmware/docker-volume-vsphere/vmdk_plugin/drivers/vmdk/vmdk_driver.go:251 +0x12f3 fp=0xc82003f8e0 sp=0xc82003f5c0
...
```

**Comment by ashahi1** [comment] 2017-02-25 22:34
I hit this issue again with fresh setup. This was the first volume I was trying to create on the setup.

Fresh log files have been attached:
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/801559/vmdk_ops.txt)
[docker-volume-vsphere.txt](https://github.com/vmware/docker-volume-vsphere/files/801558/docker-volume-vsphere.txt)

Steps:
1. Tried creating a volume vol1 of size 10gb. Got error.
```
root@photon-xVmYMbyTn [ ~ ]# docker volume create --driver=vmdk --name=vol1 -o size=10gb
Error response from daemon: create vol1: Post http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: ContentLength=39 with Body length 0
```
2. Did docker volume ls and I could see vol1 listed
```
root@photon-xVmYMbyTn [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vmdk                vol1@sharedVmfs-0
```
3. Did docker volume inspect on vol1 and could see vol as 'attached'
```
root@photon-xVmYMbyTn [ ~ ]# docker volume inspect vol1
[
    {
        "Name": "vol1",
        "Driver": "vmdk",
        "Mountpoint": "/mnt/vmdk/vol1",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "attached to VM": "photon-VM0.1",
            "capacity": {
                "allocated": 0,
                "size": "10GB"
            },
            "clone-from": "None",
            "created": "Sat Feb 25 22:10:38 2017",
            "created by VM": "photon-VM0.1",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "attached" <<<<<<<<<<<<<<<
        },
        "Labels": {},
        "Scope": "global"
    }
]
```
4. Tried removing the volume - failed
```
root@photon-xVmYMbyTn [ ~ ]# docker volume rm vol1
Error response from daemon: Error while removing volume vol1: remove vol1: VolumeDriver.Remove: Failed to remove volume /vmfs/volumes/sharedVmfs-0/dockvols/11111111-1111-1111-1111-111111111111/vol1.vmdk, in use by VM uuid = 564da371-09cf-43a3-0b87-456431da1b8e.
```

Docker engine log:
```
root@photon-xVmYMbyTn [ ~ ]# journalctl -u docker.service
-- Logs begin at Sat 2017-02-25 02:27:08 UTC, end at Sat 2017-02-25 22:12:20 UTC. --
Feb 25 02:39:03 photon-xVmYMbyTn systemd[1]: Stopped Docker Daemon.
Feb 25 02:39:04 photon-xVmYMbyTn systemd[1]: Starting Docker Daemon...
Feb 25 02:39:04 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:04.068321191Z" level=error msg="devmapper: Udev sync is not supported. This will lead to data loss and unexpected behav
ior. Install a dynamic binary to use devicemapper or select a different storage driver. For more information, see https://docs.docker.com/engine/reference/commandline/daemon/#daemon-storag
e-driver-option"
Feb 25 02:39:04 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:04.182936164Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Feb 25 02:39:04 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:04.183743967Z" level=warning msg="Your kernel does not support kernel memory limit."
Feb 25 02:39:04 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:04.183972318Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Feb 25 02:39:04 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:04.184113005Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Feb 25 02:39:04 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:04.184235163Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
Feb 25 02:39:04 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:04.184480651Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
Feb 25 02:39:04 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:04.184641556Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
Feb 25 02:39:04 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:04.184784004Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
Feb 25 02:39:04 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:04.185084299Z" level=warning msg="mountpoint for pids not found"
Feb 25 02:39:04 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:04.185562441Z" level=info msg="Loading containers: start."
Feb 25 02:39:04 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:04.226152221Z" level=info msg="Firewalld running: false"
Feb 25 02:39:05 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:05.232728584Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --b
ip can be used to set a preferred IP address"
Feb 25 02:39:05 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:05.514147893Z" level=info msg="Loading containers: done."
Feb 25 02:39:05 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:05.514592032Z" level=info msg="Daemon has completed initialization"
Feb 25 02:39:05 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:05.514790373Z" level=info msg="Docker daemon" commit=78d1802 graphdriver=overlay version=1.12.6
Feb 25 02:39:05 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:05.521129933Z" level=info msg="API listen on /var/run/docker.sock"
Feb 25 02:39:05 photon-xVmYMbyTn systemd[1]: Started Docker Daemon.
Feb 25 02:39:05 photon-xVmYMbyTn systemd[1]: Stopping Docker Daemon...
Feb 25 02:39:05 photon-xVmYMbyTn docker[388]: time="2017-02-25T02:39:05.994042236Z" level=info msg="Processing signal 'terminated'"
Feb 25 02:39:05 photon-xVmYMbyTn systemd[1]: Stopped Docker Daemon.
Feb 25 02:39:05 photon-xVmYMbyTn systemd[1]: Starting Docker Daemon...
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.033877642Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YO
U'RE DOING [!]"
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.042103165Z" level=info msg="[graphdriver] using prior storage driver \"overlay\""
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.073137685Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.073404662Z" level=warning msg="Your kernel does not support kernel memory limit."
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.073435431Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.073451339Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.073466714Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.073583466Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.073600673Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.073613291Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.073685042Z" level=warning msg="mountpoint for pids not found"
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.073901066Z" level=info msg="Loading containers: start."
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.083468063Z" level=info msg="Firewalld running: false"
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.555023109Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --b
ip can be used to set a preferred IP address"
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.859284073Z" level=info msg="Loading containers: done."
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.859583699Z" level=info msg="Daemon has completed initialization"
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.859799774Z" level=info msg="Docker daemon" commit=78d1802 graphdriver=overlay version=1.12.6
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.872683996Z" level=info msg="API listen on /var/run/docker.sock"
Feb 25 02:39:06 photon-xVmYMbyTn systemd[1]: Started Docker Daemon.
Feb 25 02:39:06 photon-xVmYMbyTn docker[567]: time="2017-02-25T02:39:06.873425153Z" level=info msg="API listen on [::]:2375"
Feb 25 22:10:40 photon-xVmYMbyTn docker[567]: time="2017-02-25T22:10:40.031648587Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/vmdk.sock/VolumeDriver.Create: Post
http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: EOF, retrying in 1s"
Feb 25 22:10:41 photon-xVmYMbyTn docker[567]: time="2017-02-25T22:10:41.033606661Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/vmdk.sock/VolumeDriver.Create: Post
http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: ContentLength=39 with Body length 0, retrying in 2s"
Feb 25 22:10:43 photon-xVmYMbyTn docker[567]: time="2017-02-25T22:10:43.034257320Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/vmdk.sock/VolumeDriver.Create: Post
http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: ContentLength=39 with Body length 0, retrying in 4s"
Feb 25 22:10:47 photon-xVmYMbyTn docker[567]: time="2017-02-25T22:10:47.043808588Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/vmdk.sock/VolumeDriver.Create: Post
http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: ContentLength=39 with Body length 0, retrying in 8s"
Feb 25 22:10:55 photon-xVmYMbyTn docker[567]: time="2017-02-25T22:10:55.044492577Z" level=error msg="Handler for POST /v1.24/volumes/create returned error: create vol1: Post http://%2Frun%
2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: ContentLength=39 with Body length 0"
Feb 25 22:12:20 photon-xVmYMbyTn docker[567]: time="2017-02-25T22:12:20.358151536Z" level=error msg="Handler for DELETE /v1.24/volumes/vol1 returned error: Error while removing volume vol1
: remove vol1: VolumeDriver.Remove: Failed to remove volume /vmfs/volumes/sharedVmfs-0/dockvols/11111111-1111-1111-1111-111111111111/vol1.vmdk, in use by VM uuid = 564da371-09cf-43a3-0b87-
456431da1b8e."
```

**Comment by ashahi1** [comment] 2017-02-25 22:38
Removed 'Need Repro' label as fresh logs have been uploaded.

**Comment by govint** [comment] 2017-02-27 08:59
From the code and @msterin's update above below is one explanation, I don't have a repro but will be testing with debug messages to see if the scenario occurs. The issue can happen if the VMCI C code didn't return an error while still a) not allocating the recv. buffer or b) returning with the buffer already freed. 

1. The VMCI client C code allocates the buffer to recieve the response from ESX.

2. Scenario 1 - If recv() fails, then the buffer allocated in vsock_get_reply() is freed, but the response structure (be_answer) still points to the memory. In EsxVmdkCmd:Run(), the logic relies on errno being set and if not it will access the buffer pointer and also try to free it.

In vsock_get_reply(),
   ret = recv(s->sock_id, a->buf, b, 0);
   if (ret == -1 || ret != b) {
      free(a->buf);   <---------- a->buf is still pointing at buf
      return CONN_FAILURE;
   }


3. Scenario 2 - If calloc() of the recv. buffer fails then vsock_get_reply() returns without setting the recv, buffer pointer to NULL. The be_answer struct is allocated with malloc and the recv. buffer pointer isn't initialized. The buf pointer is non-NULL and freeing it causes the issue.

   a->buf = calloc(1, b);
   if (!a->buf) {
         return CONN_FAILURE; <--------  a->buf isn't initialized to NULL, can be set to arbitrary value.
   }


In both above scenarios, calling free() would result in a crash. I'm not sure if errno is not getting set in the VMCI code (which library is being used for the calls made in vmci_client.c) but have added checks and posting a PR. I'll also be adding debug code to check if ever we can have a NULL buffer pointer with no error returned from Vmci_get_reply().

**Comment by govint** [comment] 2017-03-01 05:11
Ran the changes in a loop to create and remove a volume of size 10GB, the logs added didn't occur even once and create never failed. But I did notice "failed to start watcher" messages after some time and also "too many files opened" on the docker host. But that apart the issue isn't reproducing.

I can handle the comments and submit this change for now till we get more clues on the issue. The handling of C pointers in Go code and the reverse seem ok, except for the identified cases. Error handling looks ok in the GO code.

CC @pdhamdhere @msterin

**Comment by msterin** [comment] 2017-03-01 05:50
> "failed to start watcher" messages after some time and also "too many files opened" 
sounds like a leak. Which files we even open  ?

> I can handle the comments and submit this change
setting a->buf to NULL and changing to calloc seems like a safe change.  please push the final suggestion

**Comment by ashahi1** [comment] 2017-03-01 20:33
Not sure how important it is but just to add little info here - I have run into this issue  thrice, and it is the first volume creation is what gives this problem where volume creation will throw error and docker inspect will show volume as attached.

**Comment by pshahzeb** [comment] 2017-03-02 01:41
Reproduced a similar issue, to delete a volume.

```
root@photon-xVmYMbyTn [ ~ ]# docker volume rm vol_test_1@sharedVmfs-0
Error response from daemon: Error while removing volume vol_test_1@sharedVmfs-0: remove vol_test_1@sharedVmfs-0: VolumeDriver.Remove: Failed to remove volume: Error caused by file /vmfs/volumes/58b66970-bbd16a8d-f53a-02001f277ec1/dockvols/11111111-1111-1111-1111-111111111111/vol_test_1.vmdk
```

The inspect command shows the volume is still attached.
```
root@photon-xVmYMbyTn [ ~ ]# docker volume inspect vol_test_1@sharedVmfs-0
[
    {
        "Name": "vol_test_1@sharedVmfs-0",
        "Driver": "vsphere",
        "Mountpoint": "/mnt/vmdk/vol_test_1@sharedVmfs-0",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": 0,
                "size": "200MB"
            },
            "clone-from": "None",
            "created": "Wed Mar  1 19:05:54 2017",
            "created by VM": "photon-VM0.0",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "attached"
        },
        "Labels": {},
        "Scope": "global"
    }
]
```
This was encountered when the volume above was the first volume I tried to create, and it failed.
The error was same as the one pointed out by @shuklanirdesh82  earlier; which is
```
Error response from daemon: create vol_test_1: Post http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: ContentLength=39 with Body length 0
```
It is tough to reproduce this and my assumption is that the above error was due to socket error.

**Comment by govint** [comment] 2017-03-02 03:38
The remove error happens because of the way the create failed

**Comment by govint** [comment] 2017-03-05 06:27
Closing in favor of handling the same issue via #881. The issue is consistently reproduced in running the concurrent tests and this issue is the same error seen there.

**Closed by govint** 2017-03-05 06:27 UTC
Labels: kind/bug, P0
