### ISSUE TITLE
Able to add vm to the _DEFAULT vm-group

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1125] opened 2017-03-31 00:57 UTC
Steps:
1. Verified that we only have _DEFAULT tenant.
2. Tried adding vm to the _DEFAULT tenant - successful

Should this be allowed? 

------------------------------

Steps and their output are as follows:

- Only _DEFAULT tenant is present on the ESX.
```
[root@sc-rdops-vm16-dhcp-225-107:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group ls
Uuid                                  Name      Description                 Default_datastore  VM_list
------------------------------------  --------  --------------------------  -----------------  -------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is a default vm-group

```
- Able to add two VMs to the _DEFAULT tenant
```
[root@sc-rdops-vm16-dhcp-225-107:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group vm add --name=_DEFAULT --vm-list=ubuntu-VM0.2
vm-group vm add succeeded
[root@sc-rdops-vm16-dhcp-225-107:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group ls
Uuid                                  Name      Description                 Default_datastore  VM_list
------------------------------------  --------  --------------------------  -----------------  ------------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is a default vm-group                     ubuntu-VM0.2

[root@sc-rdops-vm16-dhcp-225-107:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group vm add --name=_DEFAULT --vm-list=ubuntu-VM1.2
vm-group vm add succeeded
[root@sc-rdops-vm16-dhcp-225-107:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group ls
Uuid                                  Name      Description                 Default_datastore  VM_list
------------------------------------  --------  --------------------------  -----------------  -------------------------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is a default vm-group                     ubuntu-VM0.2,ubuntu-VM1.2

[root@sc-rdops-vm16-dhcp-225-107:~]

```

Logs: 
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/884230/vmdk_ops.txt)

**Comment by lipingxue** [comment] 2017-03-31 17:15
I think we should not allow to add/rm/replace vms for _DEFAULT vmgroup. Any VM which is not assigned to a named vmgroup belongs to _DEFAULT vmgroup.

**Comment by shaominchen** [comment] 2017-03-31 17:43
Agree with @lipingxue. By design _DEFAULT vmgroup is a "container" for any VMs not belonging to a named vmgroup. This is surely a bug.

**Closed** 2017-04-03 23:14 UTC
Labels: kind/bug, P0
