### ISSUE TITLE
Old VM name persists in vmgroup members after photon host VM renaming in vsphere

### ISSUE THREAD

**Issue by vxav** [vmware/docker-volume-vsphere#1357] opened 2017-06-06 11:50 UTC
After renaming a Photon host VM (in vsphere) that is part of a vmgroup, the old name persist in the list of member VMs.

This prevents (at least that's what I was doing) the removal of the vmgroup.

To workaround it I opened vmdkops_config.db with SQLite Browser and removed the vm record, which allowed me to remove the vmgroup.

**Comment by msterin** [comment] 2017-06-08 01:30
@pshahzeb - looks like we need to track for rename events in VMChangeListener to update the db.

**Comment by shaominchen** [comment] 2017-06-20 21:09
Cross-esx multi tenancy related issue and it's a corner case, so we are moving it to 0.17 release. We can pull it back if we have bandwidth since this is a customer issue.

**Comment by tusharnt** [comment] 2017-07-17 17:34
[Cross ESX multi tenancy feature](https://github.com/vmware/docker-volume-vsphere/blob/master/docs/user-guide/admin-cli.md#config-authorization-db-configuration) is experimental.So pushing issue on the back burner for now.

@vxav Please take a look at our current design. We would love to hear your feedback!

**Comment by shaominchen** [comment] 2017-09-28 22:24
Correctness issue - marking as mustfix for Kubecon release.

**Comment by shuklanirdesh82** [comment] 2017-10-09 18:48
@vxav can you please try with the latest (0.17 release VIB)?

I have tried on my end and couldn't reproduce the reported issue, sharing the steps with you that I have performed.

Using latest VIB: `0.17.c2aef31`
```
[root@promc-2n-dhcp105-97:~] esxcli storage guestvol status
=== Service: 
Version: 0.17.c2aef31-0.0.1
Status: Running
Pid: 8147852
Port: 1019
LogConfigFile: /etc/vmware/vmdkops/log_config.json
LogFile: /var/log/vmware/vmdk_ops.log
LogLevel: INFO
=== Authorization Config DB: 
DB_LocalPath: /etc/vmware/vmdkops/auth-db
DB_SharedLocation: N/A
DB_Mode: SingleNode (local DB exists)
```

Steps performed
1. check out vmgroup listing
```
[root@promc-2n-dhcp105-97:~] esxcli storage guestvol vmgroup ls
Uuid                                  Name      Description                  Default_datastore  VM_list
------------------------------------  --------  ---------------------------  -----------------  -------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is the default vmgroup  _VM_DS      
```

2. create vmgroup `T11`
```
[root@promc-2n-dhcp105-97:~] esxcli storage guestvol vmgroup create --name=T11 --vm-list=photon2 --default-datastore=datastore1
vmgroup 'T11' is created. Do not forget to run 'vmgroup vm add' to add vm to vmgroup.
[root@promc-2n-dhcp105-97:~] esxcli storage guestvol vmgroup ls
Uuid                                  Name      Description                  Default_datastore  VM_list
------------------------------------  --------  ---------------------------  -----------------  -------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is the default vmgroup  _VM_DS                    
b29b73ef-698b-4a2d-93e5-67874c97c54f  T11                                    datastore1         photon2
```

3. rename vm `photon2` => `photon3`
4. invoke ```vmgroup ls``` again
```
[root@promc-2n-dhcp105-97:~] esxcli storage guestvol vmgroup ls
Uuid                                  Name      Description                  Default_datastore  VM_list
------------------------------------  --------  ---------------------------  -----------------  -------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is the default vmgroup  _VM_DS                    
b29b73ef-698b-4a2d-93e5-67874c97c54f  T11                                    datastore1         photon3
```
5. remove vm from vm group and delete vmgroup
```
[root@promc-2n-dhcp105-97:~] esxcli storage guestvol vmgroup vm rm --name=T11 --vm-list=photon3
vmgroup vm rm succeeded
[root@promc-2n-dhcp105-97:~] esxcli storage guestvol vmgroup ls
Uuid                                  Name      Description                  Default_datastore  VM_list
------------------------------------  --------  ---------------------------  -----------------  -------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is the default vmgroup  _VM_DS                    
b29b73ef-698b-4a2d-93e5-67874c97c54f  T11                                    datastore1                
[root@promc-2n-dhcp105-97:~] esxcli storage guestvol vmgroup rm --name=T11
vmgroup rm succeeded
[root@promc-2n-dhcp105-97:~] esxcli storage guestvol vmgroup ls
Uuid                                  Name      Description                  Default_datastore  VM_list
------------------------------------  --------  ---------------------------  -----------------  -------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is the default vmgroup  _VM_DS   
```

**Comment by shuklanirdesh82** [comment] 2017-10-09 21:42
@vxav I am closing this issue please reopen with steps if you are still running into the issue.

**Closed by shuklanirdesh82** 2017-10-09 21:42 UTC
Labels: customer, mustfix, P0
