### ISSUE TITLE
Test improvement (go tests): Supply unique name for volume creation 

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#744] opened 2016-11-16 23:36 UTC
All test should be having unique name such as build# (while running through CI) and timestamp (on local).

CC @kerneltime

**Comment by kerneltime** [comment] 2016-11-16 23:53
This is a duplicate of https://github.com/vmware/docker-volume-vsphere/issues/509

**Closed by kerneltime** 2016-11-16 23:53 UTC
Labels: component/test-infrastructure, kind/enhancement
