### ISSUE TITLE
deb Installation doesn't survive VM restart

### ISSUE THREAD

**Issue by lachnerd** [vmware/docker-volume-vsphere#1039] opened 2017-03-16 10:12 UTC
Hi,

i'm using "docker-volume-vsphere" on some VMs running  Ubuntu 16.04.2 LTS.

I installed them as follows:
`sudo dpkg -i docker-volume-vsphere_0.12.3f64805_amd64.deb`

Everythings working fine i see my vsphere Volumes and i'm able to use them etc.

But if i restart the VM vpshere support for docker is gone.

`docker volume ls` doesn't show me any vsphere volumes, i have to install the deb again although the installed files from it are still existing (for example "/usr/local/bin/docker-volume-vsphere")

So i have to install the docker-volume-vsphere everytime system reboots wich is pretty annoying.

Any tipps on that ?

**Comment by govint** [comment] 2017-03-16 10:32
@lachnerd can you please post the file /var/log/docker-volume-vsphere.log from the VM thats showing this behavior. Post a restart the docker-volume-vsphere service should be available and can be checked either via "ps -ef|grep docker" or preferrably "service --status-all" and check the status of Docker and docker-volume-vsphere services.

**Comment by lachnerd** [comment] 2017-03-16 10:44
Hi,

thanks for answering heres the Log File:
[docker-volume-vsphere.zip](https://github.com/vmware/docker-volume-vsphere/files/847424/docker-volume-vsphere.zip)

`service --status-all` shows me only a docker service but no "docker-volume-vsphere" service
![image](https://cloud.githubusercontent.com/assets/25339466/23992468/5aa9cc0e-0a3d-11e7-958d-262f98597720.png)

But docker-volume-vsphere is working:
![image](https://cloud.githubusercontent.com/assets/25339466/23992526/8722e2b6-0a3d-11e7-9e48-b346fc404a4c.png)

**Comment by govint** [comment] 2017-03-16 11:57
@lachnerd, thanks for the plugin logs, from these the service seem to have been restarted three times with a long gap (possibly the plugin was reinstalled) between the stop and start of the plugin for the first two times.

Possibly the volume commands are getting issued ahead of the plugin getting ready to receive requests. If the issue repros then suggest checking /var/log/docker-volume-vsphere.log and seeing if the plugin has logged itself as ready to receive requests, like below,

2017-03-16 10:52:57.027745853 +0100 CET [INFO] Starting plugin driver=vsphere log_level=info config="/etc/docker-volume-vsphere.conf"
2017-03-16 10:52:57.027756311 +0100 CET [INFO] Plugin options - port=1019
2017-03-16 10:52:57.027772639 +0100 CET [INFO] Getting volume data from unix:///var/run/docker.sock
2017-03-16 10:52:57.097918685 +0100 CET [INFO] Discovered 0 volumes in use.
2017-03-16 10:52:57.097957592 +0100 CET [INFO] Docker VMDK plugin started version="vSphere Volume Driver v0.4" port=1019 mock_esx=false
2017-03-16 10:52:57.098067691 +0100 CET [INFO] Going into ServeUnix - Listening on Unix socket address="/run/docker/plugins/vsphere.sock" <------  Plugin is available to serve requests.

**Comment by msterin** [comment] 2017-03-16 18:32
@lachnerd - reading through the message you seem to be doing the following step (_please confirm so we can try to reproduce and investigate_) : 

1. install docker (**BTW - which version ?**) 
2. Install docker-volume-plugin Release 0.12 with `dpkg -i` command (no `apt-get install -f` was run) 
3. checked that the plugin works (docker volume ls ,docker volume create work) 
4. rebooted  Ubuntu 16.04.2 LTS.
5. after reboot, `docker volume ls` does not show vsphere volumes (**BTW - is there a delay in command output ?**)
6. **reinstalled** the plugin with `dpkg -i` command
7. checked `service --status-all` - no plugin there
8. checked `docker volume ls` again and it worked. 

Is it correct  ? What steps are missing / were different ? 

The plugin missing in `service --status-all`  is a bug - we won't fix it since we are moving to Docker Managed Plugins anyways, and the current plan is to have in in 0.13 by the end of March.  Meanwhile `systemctl status docker-volume-vsphere` can be used to check for the status

if you can send the results of 'journalctl -fu docker' it would help us to compare with internal test logs.

**Comment by lachnerd** [comment] 2017-03-17 10:33
Hi,

1. OS: Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64) - Docker: Docker version 17.03.0-ce, build 3a232c8 - previously installed 1.13.1 
2. yes - `sudo dpkg -i docker-volume-vsphere_0.12.3f64805_amd64.deb`
3. correct
4. correct
5. correct - and  i noticed a delay from about maybe 20 s
6. correct
7. yes no volume plugin service only docker
8. yap

`systemctl status docker-volume-vsphere` result:
![image](https://cloud.githubusercontent.com/assets/25339466/24039213/a4212c16-0b04-11e7-9cad-d1a7570247af.png)

Results of `journalctl -u docker`:
[docker-journal.zip](https://github.com/vmware/docker-volume-vsphere/files/850259/docker-journal.zip)

I tried to reproduce this on a brandnew ubuntu vm, installed 17.03.0-ce and tried to install the deb File and got an error:
![image](https://cloud.githubusercontent.com/assets/25339466/24039391/4505937e-0b05-11e7-8fd9-4f35d9215bed.png)
Unfortunately its in german - it says that it can't be installed becaus of missing docker-engine - so i think youre forced to have a migrated system from docker-engine to  docker 17.03.0-ce to install it.

**Comment by msterin** [comment] 2017-03-17 17:31
@lachnerd - thanks for the info. The last issue you are hitting is a bug in plugin .deb config which does not handle new Docker versioning scheme well. It is fixed in the master so if you build the .deb you'd get it fixed. Our current plan is to have 0.13 release around end of March and this will be fixed there too.

Unfortunately the original issue seems be be a regression introduced by Docker in 1.13 plugin engine (see reference above)

**Closed** 2017-03-21 18:35 UTC
Labels: customer, kind/bug, P0
