### ISSUE TITLE
Failed to initialize SingleNode Config DB on esx

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1936] opened 2017-10-13 03:56 UTC
CI run: https://ci.vmware.run/vmware/docker-volume-vsphere/1666

```
2017/10/13 00:27:29 Initializing the SingleNode Config DB on esx [192.168.31.19] 
2017/10/13 00:27:29 Creating volume [restart_test_volume_931106] on VM [192.168.31.163]
2017/10/13 00:27:38 Adding create access for vmgroup _DEFAULT, datastore 'vsandatastore' on esx [192.168.31.19] 

----------------------------------------------------------------------
FAIL: restart_test.go:44: RestartTestData.SetUpSuite

restart_test.go:73:
    c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc420336900), Stderr:[]uint8(nil)} ("exit status 1")
... Configuration not found. Please init configuration with 'esxcli storage guestvol config init'.

2017/10/13 00:27:39 Removing container [restart_test_container_299385 restart_test_container_420764 restart_test_container_1080449] on VM [192.168.31.163]
2017/10/13 00:27:39 Destroying volume [restart_test_volume_931106]
2017/10/13 00:27:41 Removing access for 'vsandatastore' from vmgroup _DEFAULT

----------------------------------------------------------------------
FAIL: restart_test.go:82: RestartTestData.TearDownSuite

restart_test.go:93:
    c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc4203781a0), Stderr:[]uint8(nil)} ("exit status 1")
... Configuration not found. Please init configuration with 'esxcli storage guestvol config init'.
```

**Comment by shuklanirdesh82** [comment] 2017-10-16 23:43
@govint Please adjust the Estimate after your investigation.

**Comment by govint** [comment] 2017-10-24 06:37
The build seems to have succeeded (was it restarted?) in any case its not shown up since the time this issue was reported. Lets see if it gets a repro and debug that via a new issue. Am closing this one as _not reproduced_.

**Closed by govint** 2017-10-24 06:37 UTC
Labels: kind/bug, mustfix, P1
