### ISSUE TITLE
Investigate/Optimize overhead of using admin commands through esxcli

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1872] opened 2017-09-07 18:20 UTC
Usage of admin commands through esxcli seems to have increased the command latency a bit. This builds up and is evident through e2e tests which fire multiple admin commands over ssh.

This needs investigation and if possible optimize the latency of commands.

**Comment by pshahzeb** [comment] 2017-09-08 06:02
Following result shows accumulation of overhead when I ran one admin command i.e. vmgroup ls in a loop 50 times.

```
[root@sc2-rdops-vm03-dhcp-116-226:~] cat test_raw.sh
c=1
while [ $c -le 50 ]
do
        /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup ls
        c=$((c+1))
done
```

```
real	0m 18.16s
user	0m 0.02s
sys	0m 0.00s

real	0m 18.55s
user	0m 0.02s
sys	0m 0.00s

real	0m 18.30s
user	0m 0.02s
sys	0m 0.00s

real	0m 18.40s
user	0m 0.02s
sys	0m 0.00s

real	0m 18.79s
user	0m 0.02s
sys	0m 0.00s
```

Then running esxcli based admin command
```
[root@sc2-rdops-vm03-dhcp-116-226:~] cat test.sh
c=1
while [ $c -le 50 ]
do
        esxcli storage guestvol vmgroup ls
        c=$((c+1))
done
```
```
real	0m 34.25s
user	0m 0.02s
sys	0m 0.00s


real	0m 33.30s
user	0m 0.02s
sys	0m 0.00s


real	0m 34.06s
user	0m 0.02s
sys	0m 0.00s

real	0m 33.46s
user	0m 0.02s
sys	0m 0.00s

real	0m 33.45s
user	0m 0.02s
sys	0m 0.00s
```

Profiling info of a single command for ```esxcli storage guestvol vmgroup ls```

```
326718 function calls (325559 primitive calls) in 1.128 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.004    0.004    1.129    1.129 /bin/esxcli:7(<module>)
        1    0.000    0.000    0.727    0.727 /bin/esxcli:2352(main)
        1    0.000    0.000    0.727    0.727 /bin/esxcli:482(HandleCmdline)
        1    0.000    0.000    0.710    0.710 /bin/esxcli:460(_HandleOneCmd)
       10    0.000    0.000    0.707    0.071 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py:542(<lambda>)
       10    0.000    0.000    0.707    0.071 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py:333(_InvokeMethod)
       10    0.001    0.000    0.706    0.071 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py:1215(InvokeMethod)
       10    0.001    0.000    0.435    0.044 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/httplib.py:1037(getresponse)
       10    0.000    0.000    0.430    0.043 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/httplib.py:408(begin)
       85    0.011    0.000    0.427    0.005 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/socket.py:406(readline)
     2050    0.009    0.000    0.411    0.000 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/ssl.py:707(recv)
     2050    0.006    0.000    0.401    0.000 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/ssl.py:597(read)
       10    0.000    0.000    0.397    0.040 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/httplib.py:369(_read_status)
     2050    0.394    0.000    0.394    0.000 {method 'read' of '_ssl._SSLSocket' objects}
        1    0.000    0.000    0.393    0.393 /bin/esxcli:1084(_Execute)
        1    0.018    0.018    0.331    0.331 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/__init__.py:9(<module>)
    26/10    0.000    0.000    0.323    0.032 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/Cache.py:11(fnCache)
        1    0.000    0.000    0.315    0.315 /bin/esxcli:1018(_ParseCLIArgs)
        1    0.000    0.000    0.314    0.314 /bin/esxcli:900(_GetApps)
...
```

There isn't an obvious bottleneck here. The actual command (vmdkops_admin.py vmgroup ls) gets executed through ```_Execute``` function which only takes 0.393s out of total 1.128s latency.
The overhead of around argparsing and invoking command inside esxcli is probably constant, but builds up over multiple calls (as we do in our tests)

**Comment by shaominchen** [comment] 2017-09-08 18:31
Great analysis! So it confirms that esxcli does increase the command latency quite a lot. One single esxcli call takes about 0.736 second (including profiling overhead), which seems quite slow.

Based on above profiling logs, I don't think we can do much on our side. One thing we can do is to send a query to esxcli team to confirm if this latency is expected or not. As a wrapper for underlying cmds, this latency caused by esxcli overhead is really non-trivial.

**Comment by govint** [comment] 2017-09-08 19:05
is the latency owing to having a script based plugin for admin CLI via esxcli vs. builtin? That may explain the timing?

**Comment by pshahzeb** [comment] 2017-09-11 19:11
May be we can achieve a bit better number through builtin but not much.
See below profiling of esxcli system time get which is served through native code

```
 305624 function calls (304497 primitive calls) in 0.611 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.004    0.004    0.611    0.611 /bin/esxcli:7(<module>)
        1    0.015    0.015    0.314    0.314 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/__init__.py:9(<module>)
        1    0.000    0.000    0.233    0.233 /bin/esxcli:2352(main)
        1    0.000    0.000    0.233    0.233 /bin/esxcli:482(HandleCmdline)
       10    0.000    0.000    0.218    0.022 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py:542(<lambda>)
       10    0.000    0.000    0.218    0.022 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py:333(_InvokeMethod)
        1    0.000    0.000    0.218    0.218 /bin/esxcli:460(_HandleOneCmd)
       10    0.000    0.000    0.218    0.022 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py:1215(InvokeMethod)
     24/8    0.000    0.000    0.214    0.027 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/Cache.py:11(fnCache)
        1    0.000    0.000    0.207    0.207 /bin/esxcli:1018(_ParseCLIArgs)
        1    0.000    0.000    0.207    0.207 /bin/esxcli:900(_GetApps)
     4114    0.033    0.000    0.195    0.000 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py:614(CreateDataType)
        1    0.000    0.000    0.181    0.181 /bin/esxcli:778(_GetCLIInfo)
        1    0.007    0.007    0.173    0.173 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/ServerObjects.py:2(<module>)
       10    0.000    0.000    0.152    0.015 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py:734(Deserialize)
       10    0.006    0.001    0.152    0.015 {built-in method ParseFile}
        1    0.000    0.000    0.108    0.108 /bin/esxcli:761(_GetCLIInfoHelper)
     1102    0.002    0.000    0.091    0.000 /build/mts/release/bora-3355834/cayman_python/python/src/Modules/pyexpat.c:566(StartElement)
     1072    0.012    0.000    0.089    0.000 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py:567(StartElementHandler)
        1    0.000    0.000    0.079    0.079 /bin/esxcli:725(_GetAllMoInstances)
    18866    0.033    0.000    0.073    0.000 {method 'join' of 'str' objects}
  392/296    0.000    0.000    0.073    0.000 {getattr}
        2    0.000    0.000    0.073    0.036 /bin/esxcli:663(_GetCLIStub)
        5    0.000    0.000    0.073    0.015 /bin/esxcli:620(_GetSessionAttr)
        2    0.000    0.000    0.073    0.036 /bin/esxcli:653(_GetContent)
...
...
        1    0.000    0.000    0.011    0.011 /bin/esxcli:1084(_Execute)
       10    0.000    0.000    0.010    0.001 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/httplib.py:999(request)
       10    0.000    0.000    0.010    0.001 /build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/httplib.py:1020(_send_request)
...
```
The actual execution in _Execute takes less time. There is still overhead.

The script based plugin is read when hostd comes up and namespace is made available. So I think at the end of the day, while executing a command, the builtin and plugin based commands should have almost same performance.

**Comment by govint** [comment] 2017-09-12 11:49
[esxcli-time.txt](https://github.com/vmware/docker-volume-vsphere/files/1295801/esxcli-time.txt)
[admincli-time.txt](https://github.com/vmware/docker-volume-vsphere/files/1295800/admincli-time.txt)

Ran the script on a setup with just the default vmgroup and no config,

 /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py config status
DB_Mode: NotConfigured (no local DB, no symlink to shared DB)
DB_SharedLocation: N/A
DB_LocalPath: N/A

**Comment by govint** [comment] 2017-09-12 12:15
Created five more vmgroups (no VMs in them) and tried the same test, again no real difference between admin CLI and esxcli
[esxcli-withDB-5vgs.txt](https://github.com/vmware/docker-volume-vsphere/files/1295875/esxcli-withDB-5vgs.txt)
[admincli-withDB-5vgs.txt](https://github.com/vmware/docker-volume-vsphere/files/1295876/admincli-withDB-5vgs.txt)

**Comment by shuklanirdesh82** [comment] 2017-09-29 19:00
mustfix for atleast investigation task

**Comment by govint** [comment] 2017-11-27 11:42
Closing, please open if there is a need even to check these timings. Going forwards, host level container related operations is highly unlikely and at best avoided. Split interfaces between guest and host are not going to be useful at all - user wants a single interface vs. many. Plus the one aspect of datastore level multi-tenancy is not clear why users would ever want that - given kunernetes + storage classes + CSI is the way forward, host level tenant mgmt. seems like something thats worth deprecating.

**Closed by govint** 2017-11-27 11:42 UTC
Labels: Investigate, P1, performance
