### ISSUE TITLE
[Need repro]Volume create failed as docker daemon was unavailable

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1412] opened 2017-06-14 04:41 UTC
Volume create failed due to error : Cannot connect to the Docker daemon at unix:///var/run/docker.sock.  
CI: https://ci.vmware.run/vmware/docker-volume-vsphere/500

Did not see this issue while running tests locally. 

Not sure if this issue is same as #1395

VM: 192.168.31.81
ESX: 192.168.31.62

=> Test log:
```
2017/06/14 02:56:33 Creating volume [vg_basictest_volume_6smhcwuuqly8] on VM [192.168.31.81]
2017/06/14 02:56:41 Deleting a vmgroup [vg_basictest] on esx [192.168.31.62]

----------------------------------------------------------------------
FAIL: vmgroupbasic_test.go:117: vgBasicSuite.TestVmgroupOfOrphanedVolumes

vmgroupbasic_test.go:131:
    c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc420180aa0), Stderr:[]uint8(nil)} ("exit status 1")
... Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

=> Log VM1 192.168.31.81

```
2017-06-14 02:54:01.154837116 +0000 UTC [INFO] Removing volume name="defaultVG_volume_1twm86kqk9z67" 
2017-06-14 02:56:52.05005974 +0000 UTC [INFO] No config file found. Using defaults.
2017-06-14 02:56:52.055197975 +0000 UTC [WARNING] Failed to load config file /etc/docker-volume-vsphere.conf: open /etc/docker-volume-vsphere.conf: no such file or directory
2017-06-14 02:56:52.055217009 +0000 UTC [INFO] Starting plugin driver=vsphere log_level=info config="/etc/docker-volume-vsphere.conf" 
2017-06-14 02:56:52.055249354 +0000 UTC [INFO] Plugin options - port=1019 
2017-06-14 02:56:52.055263333 +0000 UTC [INFO] Getting volume data from unix:///var/run/docker.sock
2017-06-14 02:56:54.056308995 +0000 UTC [INFO] Can't connect to unix:///var/run/docker.sock due to (An error occurred trying to connect: context deadline exceeded), skipping discovery
2017-06-14 02:56:54.056378673 +0000 UTC [INFO] Refcounting failed: (An error occurred trying to connect: context deadline exceeded).
2017-06-14 02:56:54.056402927 +0000 UTC [INFO] Docker VMDK plugin started version="vSphere Volume Driver v0.4" port=1019 mock_esx=false 
2017-06-14 02:56:54.056602758 +0000 UTC [INFO] Going into ServeUnix - Listening on Unix socket address="/run/docker/plugins/vsphere.sock" 
```

/CC @govint

**Comment by govint** [comment] 2017-06-15 06:38
Around the time that the daemon is unavailable the docker daemon has logged these logs. It seems like an issue with docker but we need to check if its reproducible.

Jun 14 02:56:40 sc-rdops-vm18-dhcp-57-89 dockerd[9810]: time="2017-06-14T02:56:40.848735108Z" level=error msg="agent: session failed" error="rpc error: code = 14 desc = grpc: the connection is unavailable" module="node/agent" node.id=t0xuag04tgh722r9z3yur3v5y

Jun 14 02:56:41 sc-rdops-vm18-dhcp-57-89 dockerd[9810]: time="2017-06-14T02:56:41.857635371Z" level=error msg="Failed to join memberlist [192.168.31.81] on retry: 1 error(s) occurred:\n\n* Failed to join 192.168.31.81: dial tcp 192.168.31.81:7946: i/o timeout"

Jun 14 02:56:42 sc-rdops-vm18-dhcp-57-89 dockerd[9810]: time="2017-06-14T02:56:42.755470017Z" level=error msg="agent: session failed" error="rpc error: code = 14 desc = grpc: the connection is unavailable" module="node/agent" node.id=t0xuag04tgh722r9z3yur3v5y

Jun 14 02:56:45 sc-rdops-vm18-dhcp-57-89 dockerd[9810]: time="2017-06-14T02:56:45.226731216Z" level=error msg="agent: session failed" error="rpc error: code = 14 desc = grpc: the connection is unavailable" module="node/agent" node.id=t0xuag04tgh722r9z3yur3v5y

Jun 14 02:56:49 sc-rdops-vm18-dhcp-57-89 dockerd[9810]: time="2017-06-14T02:56:49.908366353Z" level=error msg="agent: session failed" error="rpc error: code = 14 desc = grpc: the connection is unavailable" module="node/agent" node.id=t0xuag04tgh722r9z3yur3v5y

For now I'm not proposing any change for this issue. It seems like its a one-off case and specific to the test set up (unable to join the swarm?) issue.

If not reproduced till this weekend then will close this issue.

**Comment by shaominchen** [comment] 2017-06-20 21:17
@govint Looks like you are working on this. Feel free to move to next release if this can't be addressed in the current release.

**Comment by govint** [comment] 2017-06-21 17:55
I'm closing this and open a new issue if the issue recurs

**Closed by govint** 2017-06-21 17:55 UTC
Labels: kind/bug, P1
