### ISSUE TITLE
Error occurred while creating docker volume and allocated capacity stays at '0' - vm was created on ESX 6.0U2

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#656] opened 2016-10-27 18:19 UTC
**Steps to reproduce**:
1. create photon vm on esx 6.0U2
2. check docker version and update to 1.12 if it is not
3. Install docker-volume-driver-vsphere-v0-7 by performing steps mentioned at http://cormachogan.com/2016/10/06/nice-enhancements-docker-volume-driver-vsphere-v0-7/ till step #6 (restart docker)
4.  create docker volume using following command
docker volume create --driver=vmdk --name=testVol -o size=10gb

**expectation**: volume should be created correctly

While creating docker volume very first time; runs into following issue. It lists down the volume as created even though the error. While inspecting it, it seems space is not allocated to it. 

**Note**: All subsequent volume creation request are succeeded. 

```
# docker volume create --driver=vmdk --name=testVol -o size=10gb
Error response from daemon: create testVol: Post http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: ContentLength=42 with Body length 0

# docker run --rm -it -v testVol:/mnt/myvol2 busybox`
docker: Error response from daemon: VolumeDriver.Mount: Failed to mount device /dev/disk/by-path/pci-0000:0b:00.0-scsi-0:0:0:0 at /mnt/vmdk/testVol: invalid argument.
```

**Output** of docker inspect:

```
# docker volume inspect testVol
[
    {
        "Name": "testVol",
        "Driver": "vmdk",
        "Mountpoint": "/mnt/vmdk/testVol",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "attached to VM": "p3",
            "capacity": {
                **"allocated": 0**,
                "size": "10GB"
            },
            "created": "Thu Oct 27 16:13:13 2016",
            "created by VM": "p3",
            "datastore": "datastore",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "attached"
        },
        "Labels": {},
        "Scope": "global"
    }
]

# docker volume ls
DRIVER              VOLUME NAME
vmdk                testVol

# docker run --rm -it -v testVol:/mnt/myvol2 busybox
docker: Error response from daemon: VolumeDriver.Mount: Failed to mount device /dev/disk/by-path/pci-0000:0b:00.0-scsi-0:0:0:0 at /mnt/vmdk/testVol: invalid argument.

```

----------------------------docker-volume-vsphere.log-------------------------

```
2016-10-27 16:09:40.957424957 +0000 UTC [INFO] No config file found. Using defaults.
2016-10-27 16:09:40.957547447 +0000 UTC [INFO] Docker VMDK plugin started version="VMDK Volume Driver v0.3" port=1019 mock_esx=false log_level=info config="/etc/docker-volume-vsphere.conf"
2016-10-27 16:09:40.96049135 +0000 UTC [INFO] Getting volume data from unix:///var/run/docker.sock
2016-10-27 16:09:40.967452069 +0000 UTC [INFO] Discovered 0 volumes in use.
2016-10-27 16:09:40.967498918 +0000 UTC [INFO] Going into ServeUnix - Listening on Unix socket address="/run/docker/plugins/vmdk.sock"
2016-10-27 16:10:23.895138306 +0000 UTC [WARNING] Received signal signal=terminated
2016-10-27 16:10:23.940491847 +0000 UTC [INFO] No config file found. Using defaults.
2016-10-27 16:10:23.940573749 +0000 UTC [INFO] Docker VMDK plugin started port=1019 mock_esx=false log_level=info config="/etc/docker-volume-vsphere.conf" version="VMDK Volume Driver v0.3"
2016-10-27 16:10:23.940668884 +0000 UTC [INFO] Getting volume data from unix:///var/run/docker.sock
2016-10-27 16:10:23.940921578 +0000 UTC [INFO] Can't connect to unix:///var/run/docker.sock, skipping discovery
2016-10-27 16:10:23.940963993 +0000 UTC [INFO] Going into ServeUnix - Listening on Unix socket address="/run/docker/plugins/vmdk.sock"
2016-10-27 16:13:13.955374874 +0000 UTC [INFO] Attaching volume and creating filesystem name=testVol fstype=ext4
2016-10-27 16:13:17.4000578 +0000 UTC [INFO] No config file found. Using defaults.
2016-10-27 16:13:17.400214239 +0000 UTC [INFO] Docker VMDK plugin started port=1019 mock_esx=false log_level=info config="/etc/docker-volume-vsphere.conf" version="VMDK Volume Driver v0.3"
2016-10-27 16:13:17.400307603 +0000 UTC [INFO] Getting volume data from unix:///var/run/docker.sock
2016-10-27 16:13:17.419323106 +0000 UTC [INFO] Discovered 0 volumes in use.
2016-10-27 16:13:17.419388905 +0000 UTC [INFO] Going into ServeUnix - Listening on Unix socket address="/run/docker/plugins/vmdk.sock"
2016-10-27 16:17:46.320818663 +0000 UTC [INFO] Mounting volume name=testVol
2016-10-27 16:17:48.132113018 +0000 UTC [WARNING] Reached timeout while waiting for device, trying to mount anyways name=testVol timeout=1s device="/dev/disk/by-path/pci-0000:0b:00.0-scsi-0:0:0:0"
2016-10-27 16:17:48.134081292 +0000 UTC [ERROR] Failed to mount name=testVol error="Failed to mount device /dev/disk/by-path/pci-0000:0b:00.0-scsi-0:0:0:0 at /mnt/vmdk/testVol: invalid argument"
2016-10-27 16:17:48.2998454 +0000 UTC [INFO] Unmounting Volume name=testVol
2016-10-27 16:17:48.299915929 +0000 UTC [ERROR] Failed to unmount volume. Now trying to detach... mountpoint="/mnt/vmdk/testVol" error="invalid argument"
2016-10-27 16:17:53.962237431 +0000 UTC [INFO] Mounting volume name=testVol
2016-10-27 16:17:54.762551126 +0000 UTC [INFO] Attach complete event="/dev/disk/by-path/pci-0000:0b:00.0-scsi-0:0:0:0": 0x100 == IN_CREATE name=testVol
2016-10-27 16:17:54.76290828 +0000 UTC [ERROR] Failed to mount name=testVol error="Failed to mount device /dev/disk/by-path/pci-0000:0b:00.0-scsi-0:0:0:0 at /mnt/vmdk/testVol: invalid argument"
2016-10-27 16:17:54.95607713 +0000 UTC [INFO] Unmounting Volume name=testVol
2016-10-27 16:17:54.956131226 +0000 UTC [ERROR] Failed to unmount volume. Now trying to detach... mountpoint="/mnt/vmdk/testVol" error="invalid argument"
2016-10-27 17:54:59.932923821 +0000 UTC [INFO] Attaching volume and creating filesystem name=testVol1 fstype=ext4
2016-10-27 17:55:16.884498231 +0000 UTC [INFO] Volume and filesystem created fstype=ext4 name=testVol1
```

---

**Comment by govint** [comment] 2016-10-27 18:26
The photon OS used as guest does have an issue with rescanning hot-added disks.

Please do this on the Photon guest:
tdnf remove linux; tdnf install linux

or,
tdnf install linux - if it was not installed yet

The plugin formats volumes on the guest OS when its created. The above issue in the guest OS prevents the new disk from being recognized and prevents the format from happening and hence the observed behavior.

Suggest trying the above step and report if the issue is still seen.

**Comment by msterin** [comment] 2016-10-27 20:37
@govint - can you elaborate on why it works the second time ? It is still hot-added disk, so I what exactly is the "issues with rescanning hot-added disks" which hits us on the first `create` but does not do so on the second ?
The  difference seems to be that /mnt/vmdk is created, and PVSCSI controller is created on the first hit. @shuklanirdesh82   - can you try a fresh Photon , mkdir -p /mnt/vmdk, add PVSCI controller, and only then install and try the volume service ?

**Comment by shuklanirdesh82** [comment] 2016-10-29 02:31
Thanks @govint & @msterin for providing the suggestion. I have tried both approaches and here are my findings.

Using fresh VM for each run:
Before installing the plug-in i.e. docker-volume-vsphere following approaches were performed and not able to reproduce the reported issue.

Approach#1: tdnf remove linux; tdnf install linux
Approach#2: Add PVSCSI controller to photon vm [If the PVSCSI controller is present before creating volume, the reported issue is not reproducible.]

**Comment by pdhamdhere** [comment] 2016-11-04 19:16
@govint What's next step here? Add it to [Known Issues](https://github.com/vmware/docker-volume-vsphere#known-issues)?

**Comment by govint** [comment] 2016-11-05 06:50
There is no code fix for this issue, but needs documentation (Known issues) for Photon OS to first do the workaround before using docker volumes.

**Comment by kerneltime** [comment] 2016-11-23 18:31
@govint is there a PR open with Photon?  If not can you file one? or Link it here.

**Comment by pdhamdhere** [comment] 2016-11-23 19:27
Fixed in latest PhotonOS release: https://github.com/vmware/photon/issues/541

**Closed by pdhamdhere** 2016-11-23 19:27 UTC
Labels: component/server, kind/bug, wontfix
