### ISSUE TITLE
Should user be allowed to modify default vmgroup attributes [default vmgroup removal]

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1397] opened 2017-06-12 20:31 UTC
Currently user can change access rules of default vmgroup. 

Operations allowed on default vmgroup are as follows:
E.g.  
      1. Change --allow-create right to False/True, 
      2. Set max-volume-size

We have number of tests which play with configuration of default vmgroup. Need some clarity before moving ahead with test automation for default vmgroup tests.

What is our official position regarding manipulating default vmgroup? Should these operations be allowed ?

===================

Operations performed on default vmgroup their output are as follows:

1. Change allow-create to false for _DEFAULTtenant.
```
[root@sc-rdops-vm17-dhcp-4-8:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup access ls --name=_DEFAULT
Datastore  Allow_create  Max_volume_size  Total_size
---------  ------------  ---------------  ----------
_ALL_DS    True          Unset            Unset
_VM_DS     True          Unset            Unset

[root@sc-rdops-vm17-dhcp-4-8:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup access set --name=_DEFAULT --datastore=_VM_DS --allow-create=False
vmgroup access set succeeded
[root@sc-rdops-vm17-dhcp-4-8:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup access ls --name=_DEFAULT
Datastore  Allow_create  Max_volume_size  Total_size
---------  ------------  ---------------  ----------
_ALL_DS    True          Unset            Unset
_VM_DS     False         Unset            Unset
```
2. Set --volume-maxsize for _DEFAULT tenant to 2GB
```
[root@sc-rdops-vm04-dhcp-100-33:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup access set --name=_DEFAULT --datastore=_VM_DS --allow-create=True --volume-maxsize=2GB
vmgroup access set succeeded
[root@sc-rdops-vm04-dhcp-100-33:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup access ls --name=_DEFAULT
Datastore  Allow_create  Max_volume_size  Total_size
---------  ------------  ---------------  ----------
_ALL_DS    True          Unset            Unset
_VM_DS     True          2.00GB           Unset

[root@sc-rdops-vm04-dhcp-100-33:~]
```

**Comment by govint** [comment] 2017-06-13 03:25
May have had this discussion earlier, default vmgroup is best left unchanged - its a canned configuration thats not modifiable. ANy flexibility in attributes must be only in vmgroups created by the user. The DEFAULT vmgroup should really never be used at all to store workload data volumes.

**Comment by ashahi1** [comment] 2017-06-13 19:41
As Govindan has highlighted, should we leave default vmgroup unchanged?

/ CC @msterin @pdhamdhere @shaominchen @tusharnt

**Comment by shaominchen** [comment] 2017-06-13 20:50
I had this discussion with Mark and Prashant before. My preference was that we should not allow user to modify DEFAULT vmgroup. Even after Mark had explained the design intent to me, I was still not fully convinced. My personal opinion is - making DEFAULt vmgroup same as others doesn't gain much, but has caused too many complexities and we have to deal with a lot of unexpected corner cases.

Since multi-tenancy is currently an experimental feature, I don't think we want to change this design right now. But in the future after we fix the open issues and make it as an official feature, I think it makes more sense to make DEFAULT vmgroup unmodifiable. I tend to agree with Govindan that the DEFAULT vmgroup should really never be used at all to store workload data volumes. It's just a convenient default configuration for customers to try out the cool features quickly without bothering to deal with tenancy.

**Comment by msterin** [comment] 2017-06-13 23:13
Can you elaborate on **why** do you think it should be a special immutable group. what use cases it will address and  **what specifically* are the complications you refer to ? 

I am not sure what would be the reason to even have "default" group if it's immutable, and how would you address the use cases like "I want all my dev Vms to be on <DS1> , and allocate 1/2 of DS1 capacity to them, and everyone else goes to DS1, which is slow, and we allocate 1/3 capacity them" ?  Feel free to take it offline though

**Comment by shaominchen** [comment] 2017-06-14 00:29
We should definitely take this offline as this is a complicated discussion :) I will just put some comments here as a memo:

I don't believe we even need default vmgroup at all if vDVS starts with multi-tenancy feature from the beginning. We started without any access control, and later added this feature based on customer feedback, but still want to keep it simple for new customers to try out this product, and also maintain a seamless user experience for existing customers to transition from old mode (no access control) to new mode (with access control). Default vmgroup is a great idea/solution that addressed all these requirements.

However, allowing user to modify system-predefined default vmgroup, or mixing default vmgroup with user-defined vmgroup is not really a good idea. We have already run into quite some awkward scenarios (@lipingxue) where the implementation becomes very complicated and buggy. I don't want to spend time to list all those issues right now, but we can definitely discuss in the future.

In my opinion, default vmgroup should only be used as a sandbox in which user can try out vDVS. After initial experiment, once user starts to use vDVS in production, the default vmgroup should simply be locked down. All production volumes should be created in user-defined vmgroups. The vmgroup design should provide enough flexibility to support all kinds of access control scenarios without default vmgroup.

**Comment by msterin** [comment] 2017-06-14 01:09
> However, allowing user to modify system-predefined default vmgroup, or mixing default vmgroup with user-defined vmgroup is not really a good idea. 

Why ? You need to spell out use cases. Implementation we can improve. 

> All production volumes should be created in user-defined vmgroups.

Why ? Other than exiting implementation complexities, I do not hear any arguments. I understand your view but it's hard to agree or disagree when there are no arguments

**Comment by shaominchen** [comment] 2017-06-14 05:11
I don't think there are any use cases we can't support without default vmgroup. Let's take your use case above as an example (BTW, I think you meant "everyone else goes to DS2", right?). We can support that easily by introducing regular expressions for VM names. Currently our logic does *exact match* between vm_uuid and tenant, which is really unusual in a typical algorithm of authorization engine. Just introducing one more level of indirection (i.e. vm_uuid -> vm_name -> tenant), we will get a more flexible authorization algorithm and make the problem easier to resolve.

I really don't want to get into more detailed discussions on this topic right now, so I will stop here :)

**Comment by govint** [comment] 2017-06-14 10:01
The issue is also this,
1. To view access attrs for the DEFAULT tenant the DB has to be there (auth_api.py:_tenant_access_ls()). Because, when the DB is created, the default vmgroup is created in it with the _VM_DS and _ALL_DS entries.
1. But the other parts of the code assume these values (VM_DS) which seems inconsistent.
1. So, if we want to be able to update default vmgroup attributes then we need the DB to persist that or add code to hold that in memory which is lost across restarts of the plugin.

These fixes can be done but do we want to do that now with the number of tests that are pending to be developed. I'd suggest lets document these and fix only whats obviously buggy.

If it takes more code to fix the bug (reverting max/total volume sizes) then lets disallow setting these in the first place.

**Comment by govint** [comment] 2017-06-14 12:55
Please see update in #1396, the changes to get the CLI commands all working reliably with the DEFAULT vmgroup are much more and  unnecesary (can create more bugs if not fixed correctly). A refactoring exercise would be needed to ensure the code can handle requests on the DEFAULT vmgroup.

For example, the auth-api code expects that a DB exist in order to access/update any vmgroup. Changing that seems to need more changes in a trail of functions. Preferrably this should be a refactoring exercise after identifying all the changes. Possbly after the present set of test functions are all developed.

**Comment by msterin** [comment] 2017-06-14 15:17
@shaominchen, @govint - let's finalize the behavior and make it final  (I thought we did have agreement the last time around though), before.making decisions on simply cutting it.

**Comment by govint** [comment] 2017-06-20 08:47
Related to #1441

**Comment by govint** [comment] 2017-07-05 11:30
This is more a question vs. a bug needing a code fix. Closing and can be taken offline.

**Comment by ashahi1** [comment] 2017-07-05 19:08
Until we come to conclusion on whether properties of default vmgroup are modifiable, I think we should leave this issue open. Reopening this issue.

**Comment by govint** [comment] 2017-07-24 08:17
Its not a P0 issue as there isn't going to be any code changes and I'm not making this decision either. Right now issues that depend on this decision are moved to "Future" #1520  for example.

**Comment by shuklanirdesh82** [comment] 2017-07-26 01:54
> Right now issues that depend on this decision are moved to "Future" #1520 for example.

#1520 is for the test automation being blocked on this issue. 

> What is our official position regarding manipulating default vmgroup? Should these operations be allowed ?

Reference: https://github.com/vmware/docker-volume-vsphere/issues/1397#issue-235356286

I guess this is opened to get closure before GA. If we'll agree to treat `_DEFAULT` the same as "user created named group" then we should close this as `invalid`.

@govint if you are agree then please close as `invalid`; pulling back to current sprint to decide.

**Comment by govint** [comment] 2017-07-26 03:54
Its agreed that removing the default vmgroup is ok, but attendant bugs aren't and those must be fixed.

**Closed by govint** 2017-07-26 03:54 UTC
Labels: kind/Feature, P2
