### ISSUE TITLE
Add tests for perf/scale, per goals in spec

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#63] opened 2016-02-16 20:37 UTC
See https://wiki.eng.vmware.com/CNA/Storage#Kubernetes_Persistent_Data_Volume_Plugin " Perf and scale " section

Also, from customers 
- Scale  1500 VMs – flocker driver takes 20000 secs. 
- Takes a long time to deploy a container volume. vSphere docker/flocker plugin was being timed out. 
- Note: it was worked around  by restricting the search to a limited set of VM’s and automated it using python scripts.

**Comment by shuklanirdesh82** [comment] 2017-03-06 21:01
Test scenario to consider per release base:

Goal: need to track performance data per release base.

Test bed requirement (VSAN testbed is an ideal case):

- At-least one ESX & one docker host required to exercise following test steps

- [ ] Scenario 1 (basic volume creation/admin ls workflow)
Note: may extend the [test] (https://github.com/vmware/docker-volume-vsphere/blob/master/vmdk_plugin/E2E_Tests/e2e_verifyVolmProperties_test.go) 

```
Perform the scenario for single ESX host and all docker host should should be on the same ESX

1. VM1: create volume (format types: "thin", "zeroedthick", "eagerzeroedthick") > measure volume creation time for each format type
2. ESX: invoke "vmdkops_admin ls" and measure the time for CLI response
3. Extend your testbed to have at-least 1000 vms; where ~10 docker enabled vms are required  (the goal here is to have many vms in the inventory) 
4. invoke "vmdkops_admin ls" > measure the response time > compare with time retrieved from step#2
5. create ~500 volumes in total from above docker hosts (invoke request from all about 10 vms)
6. repeat step#4 -> if response time is >3 seconds raise an issue (log the error through automation script)
7. repeat step#1 -> measure time and compare with time logged during step#1 for each format types -> if time diff > 10 seconds raise an issue (log the error through automation script)

Note: leave the test bed as is to perform steps mentioned in scenario 2
```
- [ ] Scenario 2 (admin cli workflow ... testbed setup depends on scenario 1)

```
Note: ESX should be having access to multiple datastore (considering 3 datastore for our experiment e.g. local/shared-vmfs/vsan)

Tenant ls verification: invoke vmdkops_admin tenant ls -> measure time -> compare time with step #1-> if diff >3 seconds raise an issue

on ESX:
1. invoke vmdkops_admin tenant ls > measure time
2. create 100 tenants -> "Tenant ls verification"
3. add 8-10 vms to created tenants -> "Tenant ls verification"
4. add datastore access rules for each tenant for all 3 datastores -> "Tenant ls verification"
```

**Comment by shuklanirdesh82** [comment] 2017-03-06 21:04
@ashahi1 I'm assigning this to you to perform steps mentioned at https://github.com/vmware/docker-volume-vsphere/issues/63#issuecomment-284531051

As we are gathering the data very first time for 0.13 release; let's track the performance data manually at common place to treat them as baseline for going forward.

//CC @tusharnt

**Comment by shaominchen** [comment] 2017-03-07 23:36
I'd suggest to have some simple and straightforward performance tests so that if any performance issues are being detected, it's easier to figure out the root cause in those simple test steps. Some possible "simple" tests I can think of:
1. Deploy 1K VMs. Install vDVS plugin in one VM, and try to create/rm/ls volumes
2. Try to create 1K volumes sequentially, measure the total time
3. After 1K volumes are created, and try to run rm/ls commands
4. Try to create 1K volumes concurrently, measure the total time
Above tests should cover some potential bottleneck areas: DB access and Host API invocation

**Comment by msterin** [comment] 2017-03-08 03:00
Agreed with @shaominchen , with one correction - for each `run volume command` we need to time it. 

I also think 1-3 are most important, 4 is nice to have

**Comment by shuklanirdesh82** [comment] 2017-03-08 06:02
@shaominchen / @msterin 

> for each run volume command we need to time it.

Yeah that is the plan. 

> https://github.com/vmware/docker-volume-vsphere/issues/63#issuecomment-284896509

item 1 is already covered and for #2&#3 ~500 volumes creation is targeted for out initial testing (concurrently). 

Question: 

1. Does it make any difference in creating volume simultaneously or sequentially? 
2. https://github.com/vmware/docker-volume-vsphere/issues/63#issuecomment-284531051 : Step#5 is proposed to create ~500 volumes in total from 10 vms concurrently. isn't it redundant to perform sequential operation for performance profiling?

**Comment by shaominchen** [comment] 2017-03-08 06:25
@shuklanirdesh82 
1. I think creating volumes simultaneously can better simulate the usage pattern in real production environment. As Mark has mentioned, this is nice to have.
2. True. But I feel creating ~500 volumes from 10 VMs concurrently is too complicated and it doesn't  really make much difference.

**Comment by ashahi1** [comment] 2017-03-23 19:42
Test Steps:

```
1. Created 500 volumes of 100 mb each sequentially. (Time taken - 49 mins approx.)
2. After all volumes were created, did docker volume ls (~1 seconds approx.)
3. Did admin cli volume ls (~24-25 seconds approx.)
4. Removed all the volumes ( ~ 5 mins approx.)
```

Setup: 
```
4 ESXs - 364 VMs - 4 shared Vmfs datastores
Each shared vmfs has ~90 VMs.
All the VMs are powered-on.
Photon VM (Test vm) resides on sharedVmfs-0
```

All volumes were created on sharedVmfs-0 datastore (datastore on which vm resides).

I tried to deploy 500 VMs to start with these performance tests but couldn't get a setup with 500 VMs as
all the shared Vmfs datastores became inaccessible during deployment of 500 VMs. So couldn't run performance tests with 500 VMs. Will keep trying if we can increase the scale further.


Logs:
[docker-volume-vsphere.txt](https://github.com/vmware/docker-volume-vsphere/files/865962/docker-volume-vsphere.txt)
[vmdk_ops.log.1.txt](https://github.com/vmware/docker-volume-vsphere/files/865963/vmdk_ops.log.1.txt)
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/865964/vmdk_ops.txt)

**Comment by ashahi1** [comment] 2017-03-24 18:45
I executed six more runs of the following test and timed the different operations. 
```Admin cli volume ls``` seems slow so will file an issue for it.

Test Steps:
```
1. Create 500 volumes of 100 mb each sequentially.
2. Do docker volume ls and admin cli volume ls.
3. Remove all the 500 volumes.
```

Details of each run is as follows:

Run-1:
```
Individual volume creation of 100 mb : 2-3 seconds (mostly 3 and sometimes even 4)
500 Volumes creation : ~27 mins (1642 seconds)
admin cli volume ls : 32 secs
500 Volumes removal : 23 mins
Individual volume removal of 100 mb : 2-3 seconds (mostly 2)
```

Run-2:
```
Individual volume creation of 100 mb : 2-3 seconds (mostly 3)
500 Volumes creation : ~26 mins (1564 seconds)
admin cli volume ls : ~27 secs
500 Volumes removal : ~23 mins
Individual volume removal of 100 mb : ~2 seconds
```

Run-3:
```
Individual volume creation of 100 mb : 2-3 seconds (mostly 3)
500 Volumes creation : ~26 mins (1602 seconds )
admin cli volume ls : 27 secs
500 Volumes removal : ~23 mins (1409 seconds)
Individual volume removal of 100 mb : ~2 seconds
```

Run-4:
```
Individual volume creation of 100 mb : mostly 3 seconds
500 Volumes creation : ~26 mins (1560 seconds)
admin cli volume ls : 27 secs
500 Volumes removal : ~23 mins (1421 seconds)
Individual volume removal of 100 mb : ~2 seconds 
```


Run-5:
```
Individual volume creation of 100 mb : mostly 3 seconds
500 Volumes creation : ~25 mins (1558 seconds)
docker cli volume ls : ~3 seconds
admin cli volume ls : ~25 seconds
500 Volumes removal : ~23 mins (1412 seconds)
Individual volume removal of 100 mb : mostly 2 seconds
```

Run-6:
```
Individual volume creation of 100 mb : mostly 3 seconds
500 Volumes creation : ~27 mins (1645 seconds)
docker cli volume ls : ~3 seconds
admin cli volume ls : ~28 seconds 
500 Volumes removal : ~24 mins (1492 seconds)
Individual volume removal of 100 mb : ~2 seconds
```

Test logs:
[Run1.txt](https://github.com/vmware/docker-volume-vsphere/files/868859/Run1.txt)
[Run2.txt](https://github.com/vmware/docker-volume-vsphere/files/868858/Run2.txt)
[Run3.txt](https://github.com/vmware/docker-volume-vsphere/files/868862/Run3.txt)
[Run4.txt](https://github.com/vmware/docker-volume-vsphere/files/868860/Run4.txt)
[Run5.txt](https://github.com/vmware/docker-volume-vsphere/files/868863/Run5.txt)
[Run6.txt](https://github.com/vmware/docker-volume-vsphere/files/868861/Run6.txt)

Product logs:
[docker-volume-vsphere.txt](https://github.com/vmware/docker-volume-vsphere/files/868869/docker-volume-vsphere.txt)
[vmdk_ops.log.1.txt](https://github.com/vmware/docker-volume-vsphere/files/868870/vmdk_ops.log.1.txt)
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/868871/vmdk_ops.txt)


//CC @pshahzeb

**Comment by ashahi1** [comment] 2017-03-24 20:27
Issue #1083 and Issue #1072 have been filed while running these tests.

**Comment by tusharnt** [comment] 2017-03-30 18:54
Manual testing is completed.

**Closed by tusharnt** 2017-03-30 18:54 UTC
Labels: kind/test, P1, regression-test-needed

**Comment by ashahi1** [comment] 2017-03-30 19:44
- Creating large number of volumes simultaneously from single vm.

Volume creation seems slow for 100 mb size so will file an issue.

Setup:
```
One ESX  - 312 VMs 
All VMs are on one ESX
~80 VMs are powered-on  and rest are powered-off.
All VMs are on sharedVmfs-0 datastore.

```

Test will create ten threads - each thread will make 75 volumes.
Total volumes created - 750 of 100 mb each


Steps:
```
1. Create volumes simultaneously from each thread.
2. Do docker volume ls and admin cli volume ls.
3. Remove volumes simultaneously from each thread.

```

Duration for each operation is as follows:
```
One volume creation - duration fluctuated a lot but on an average it took between 25-35 seconds per volume. ~90 seconds was the maximum I saw and ~7 seconds was the minimum time it took to create one volume.

docker volume ls - ~12-14 seconds per thread
admin cli volume ls - ~180 seconds per thread
Individual volume removal - ~6-7 seconds

```

**Comment by ashahi1** [comment] 2017-03-30 19:49
- Creating large number of volumes simultaneously from 10 different VMs.

Setup:
```
One ESX  - ~300 VMs 
All VMs are on one ESX.
~80 VMs are powered-on  and rest are powered-off.
All VMs are on sharedVmfs-0 datastore.

```

Test was being run simultaneously from each vm.
Each vm was creating 40 thin provisioned volumes, 20 zeroedthick volumes and 20 eagerzeroedthick volumes. 
Total volumes created - 800 of 100 mb each.

Steps:
```
1. Create volumes (thin, zeroedthick and eagerzeroedthick) simultaneously from each vm.
2. Do docker volume ls and admin cli volume ls from each vm.
3. Remove volumes simultaneoulsy from each vm.

```
Duration (per vm) for each operation is as follows: 
```
Thin provisioned volumes - ~12-14 seconds
zeroedthick volumes - ~20 seconds
eagerzeroedthick - ~24 seconds

docker volume ls - ~ 20 seconds
admin cli volume ls - ~220 seconds
removing individual volumes - 6-7 seconds

```

Created volumes manually also on the same setup and their duration are as follows:
```
One thin volume of 100 mb - ~ 2 seconds
One eagerzeroedthick volume of 100 mb - ~ 2 seconds
One zeroedthick volume of 100 mb - ~ 3 seconds

```
