### ISSUE TITLE
User cannot delete volumes if its vmgroup gets deleted

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1469] opened 2017-06-23 02:05 UTC
Steps:
1. Create a vmgroup and add a vm to it 
2. Create a volume from the vmgroups's vm 
3. Remove the vm
4. Delete the vmgroup
5. Try deleting the volume, operation fails

Volumes should get deleted irrespective of vmgroup being present or not.

-----------------

Test steps and their output are as follows:

1. Create a vmgroup and add a vm to it 
```
[root@sc-rdops-vm05-dhcp-129-159:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup create --name vmgroup1 --default-datastore=_VM_DS --vm-list=ubuntu-VM2.2
vmgroup 'vmgroup1' is created. Do not forget to run 'vmgroup vm add' to add vm to vmgroup.
[root@sc-rdops-vm05-dhcp-129-159:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup ls
Uuid                                  Name      Description                Default_datastore  VM_list
------------------------------------  --------  -------------------------  -----------------  ------------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is a default vmgroup  _VM_DS
41bb861a-7181-4505-bacb-eda799b6c782  vmgroup1                             _VM_DS             ubuntu-VM2.2
```

2. Create a volume from the vmgroups's vm 
```
root@sc-rdops-vm02-dhcp-52-237:~# docker volume create -d vsphere:latest --name TestVol1
TestVol1
root@sc-rdops-vm02-dhcp-52-237:~# docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      TestVol1@sharedVmfs-0


[root@sc-rdops-vm05-dhcp-129-159:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py volume ls
Volume    Datastore     VMGroup   Capacity  Used  Filesystem  Policy  Disk Format  Attached-to  Access      Attach-as               Created By    Created Date
--------  ------------  --------  --------  ----  ----------  ------  -----------  -----------  ----------  ----------------------  ------------  ------------------------
TestVol1  sharedVmfs-0  vmgroup1  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  ubuntu-VM2.2  Fri Jun 23 01:45:22 2017
```

3. Remove the vm
```
[root@sc-rdops-vm05-dhcp-129-159:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup vm rm --name vmgroup1 --vm-list=ubuntu-VM2.2
vmgroup vm rm succeeded
[root@sc-rdops-vm05-dhcp-129-159:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup ls
Uuid                                  Name      Description                Default_datastore  VM_list
------------------------------------  --------  -------------------------  -----------------  -------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is a default vmgroup  _VM_DS
41bb861a-7181-4505-bacb-eda799b6c782  vmgroup1                             _VM_DS

```
4. Delete the vmgroup

```
[root@sc-rdops-vm05-dhcp-129-159:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup rm --name vmgroup1
vmgroup rm succeeded

```
5. Verified volume is still there and then tried deleting the volume - failed.
```
[root@sc-rdops-vm05-dhcp-129-159:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py volume ls
Volume    Datastore     VMGroup  Capacity  Used  Filesystem  Policy  Disk Format  Attached-to  Access      Attach-as               Created By    Created Date
--------  ------------  -------  --------  ----  ----------  ------  -----------  -----------  ----------  ----------------------  ------------  ------------------------
TestVol1  sharedVmfs-0  N/A      100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  ubuntu-VM2.2  Fri Jun 23 01:45:22 2017


root@sc-rdops-vm02-dhcp-52-237:~# docker volume rm TestVol1@sharedVmfs-0
Error response from daemon: get TestVol1@sharedVmfs-0: no such volume
root@sc-rdops-vm02-dhcp-52-237:~# docker volume rm TestVol1@sharedVmfs-0
Error response from daemon: get TestVol1@sharedVmfs-0: no such volume    <<<<<<<<<<<<<<<
root@sc-rdops-vm02-dhcp-52-237:~#
```

**Comment by govint** [comment] 2017-06-23 04:28
Suggest a vmgroup can't be removed unless

1. the volumes in the vmgroup are removed, the use case for vmgroups is to segregate users  and support multi-tenancy. Its incorrect to loose user data by allowing the vmgroup to be removed and then not be able to delete that data.
1. Optionally let the datastores be moved to another vmgroup specified by the user, so the volumes are still accessible. Moving to _DEFAULT doesn't seem correct as it makes user specific data available to all

**Comment by lipingxue** [comment] 2017-06-23 17:51
Should we allow user to remove a vmgroup if volumes in this vmgroup still exist?  Is there any specific user case that need this?  @msterin

**Comment by msterin** [comment] 2017-06-23 18:00
We have been discussing this (or similar) issues quite a few times. "Can an admin delete a group if there are object within this group". We should think about use patterns. We need to (1) make it convenient (2) prevent obvious mistakes. It is usually solved with a failure with the following message "This vmgroup still have volumes in it. Please use --force to force deletion. vmgroup and volumes will be deleted" or something like that. 

I think "block deletion of vmgroup until all is cleaned up properly" is also a reasonable approach but then we need to give user (in failure message) and easy way to do it.

**Comment by msterin** [comment] 2017-07-05 18:39
At any rate, this is `NOT A BUG`. We should not allow volume deletion from VM not authorized. 
So, the solution would be "add VM to the vmgrfoup and then delete the volume" or simply add "volume delete"  command to Admin CLI

**Comment by govint** [comment] 2017-09-13 05:11
@ashahi1, can you check the updates on the this issue and decide if this is something that can be documented vs. needing a code change to prevent vmgroup deletion.

**Comment by govint** [comment] 2017-09-28 19:50
Setting mustfix as the issue is resulting in an inconsistency where volumes can't be deleted by the user (leaks storage) because of wrong user actions in being able to delete the vmgroup without removing the volumes.  Document or code, lets resolve this.

**Comment by ashahi1** [comment] 2017-10-02 19:08
@govint I had a discussion with Sam and we felt that user should not be allowed to delete the vmgroup if their are volumes in it. So it looks like we may have to make some code changes.

//cc @shaominchen

**Closed** 2017-10-12 08:15 UTC
Labels: invalid, kind/bug, mustfix, P0
